### ISSUE TITLE
Logo in readme not clearly visible in Github dark mode.

### ISSUE THREAD

**Issue by vaidasmaciulis** [devbridge/test-juggler#110]
Logo should be updated to have white background or border for text, so it is clearly visible in dark mode

**Comment by SJellen** [comment]
<img width="600" alt="logo_white_bg" src="https://user-images.githubusercontent.com/51421669/115896487-7ba5a600-a429-11eb-88f1-a3ba0211ee02.png">


The logo had a transparent background. So I added a white one. 
I need to post it here so I can get a link to add it to the readme and do a PR.

**Comment by vaidasmaciulis** [comment]
Adding with cleaner borders:
<img width="600" alt="juggler-logo@2x-white-BG" src="https://user-images.githubusercontent.com/11597256/118511704-d84f6480-b73a-11eb-9c6f-4cc9f9fda0b8.png">
